### ISSUE TITLE
Implement GET /dataset

### ISSUE THREAD

**Issue by calvinnhieu** [chanzuckerberg/corpora-data-portal#395] opened 2020-06-18 17:28 UTC
Implement the GET /dataset/{dataset_id} endpoint to return dataset metadata and information on its artifacts.

**Comment by maniarathi** [comment] 2020-07-09 05:58
@Bento007 this should be in the Now pipeline right? and hooked up to one of your open PRs?

**Comment by Bento007** [comment] 2020-07-13 21:13
this is a duplicate of #311

**Closed by Bento007** 2020-07-13 21:13 UTC
