### ISSUE TITLE
Integrate upload SFN and ECS

### ISSUE THREAD

**Issue by mckinsel** [chanzuckerberg/corpora-data-portal#734] opened 2020-11-19 18:09 UTC
We're going to have infra defined so a lambda kicks off a step function that runs the upload.

We also have a container in ECR and a task definition and cluster in ECS.

We need to integrate those two things. We're done when invoking the lambda successfully launches the upload container.

**Comment by brianraymor** [comment] 2020-11-20 01:05
Closing as duplicate of #735

**Closed by brianraymor** 2020-11-20 01:05 UTC
Labels: Infra
