### ISSUE TITLE
Streamline deployment of chalice

### ISSUE THREAD

**Issue by Bento007** [chanzuckerberg/corpora-data-portal#379] opened 2020-06-15 21:08 UTC
Currently there are interdependencies between single-cell-infa and the deployment of chalice apps. Specifically the chalice deployment is stored in a bucket generated by single-cell-infra. Also single-cell-infra requires the api-gateway generated by chalice.

We can simplify it down to deploy chalice apps, deploy single-cell-infra, deploy frontend. This can be accomplished by storing the chalice deployed info in a parameter store or another location not managed by single-cell-infra.

**Comment by maniarathi** [comment] 2020-07-09 05:54
@Bento007 is this a duplicate of #348?

**Comment by maniarathi** [comment] 2020-07-17 21:35
Duplicate of #348, closing.

**Closed by maniarathi** 2020-07-17 21:35 UTC
