### ISSUE TITLE
Design collection management page for existing collections

### ISSUE THREAD

**Issue by pdugan20** [chanzuckerberg/corpora-data-portal#363] opened 2020-06-10 16:45 UTC
Registered users who have previously created a collection should be able to:
- View a list of all collections they own or have permissions to contribute to
- Provide the ability to create a new collection
- Toggle existing collections into a state that is editable
- Add or delete datasets to collections
- View and modify users with permissions to contribute to the collection
- Generate and copy a link to the collection
- Toggle the collection to public or private global permissions

**Comment by maniarathi** [comment] 2020-06-11 16:03
I am open to auto-saving as well (and yes it is possible). It would, however, be a nice-to-have feature later down the line since it'll involve detecting changes and then triggering the right action which is a little complex for MVP. For now, I figured a manual "save" would be the first go at it.

**Comment by liaprins-czi** [comment] 2020-06-11 16:24
Thanks @maniarathi ! I think that makes sense to me for MVP from implementation feasibility perspective.

**Comment by pdugan20** [comment] 2020-09-02 12:50
Have some early thoughts on where entry points into this page should live, and what it should look like. Work in progress designs will live: https://www.figma.com/file/ldTQ4rQu0wYR6fSXJtjDhf/collection-management?node-id=0%3A1

**Comment by brianraymor** [comment] 2020-10-06 18:49
Closing - since this is a duplicate of [Design flow for creating a collection and uploading a dataset](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell/21)

**Closed by brianraymor** 2020-10-06 18:49 UTC
Labels: ux
