### ISSUE TITLE
Extend GET /v1/collections

### ISSUE THREAD

**Issue by maniarathi** [chanzuckerberg/corpora-data-portal#646] opened 2020-10-19 19:47 UTC
## Description
Lists all collections by their UUIDs that currently exist in Corpora. If a parameter is specified as a filter, then only submissions that meet the given criteria will be returned.
## Parameters
User_ID [REQUIRED]: an OAuth ID that represents the logged in user. Returned submissions will be only ones that the given user has created.
Visibility [OPTIONAL]: the visibility of the collections to be returned which is one {PRIVATE, PUBLIC}.

## Responses
200 OK: {request_id, collection_uuid, name, description, user_id}
400 Invalid parameter

Implementation details:
- Returns all collection UUIDs that have the given visibility that have an `owner` that matches the inputted user_id.

**Comment by brianraymor** [comment] 2020-10-21 23:55
Per sprint backlog drafting, closing as duplicate of #637.

**Closed by brianraymor** 2020-10-21 23:55 UTC
Labels: backend
