### ISSUE TITLE
Unexpected errors occur during Add Dataset for a revision

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/corpora-data-portal#1310] opened 2021-07-28 23:25 UTC
When adding a dataset, I consistently see unexpected errors:

https://images.zenhubusercontent.com/228681195/4848eff4-1b5d-4a40-8f26-cd00663f7621/screen_recording_2021_07_28_at_4_22_41_pm.mov

I'm forced to manual refresh to see progress.

**Comment by tihuan** [comment] 2021-08-04 16:17
@seve @brianraymor Hmm I can't reproduce this one on staging or locally. Maybe it's fixed with all the recent changes?

Thank you!

**Comment by brianraymor** [comment] 2021-08-04 16:46
I saw it last night when I was testing the other issue. I had to refresh to continue.

**Comment by tihuan** [comment] 2021-08-04 16:55
got it thanks, Brian! @seve will try to repro too before we start debugging again!

**Comment by brianraymor** [comment] 2021-08-04 20:18
Just tried again - got it in one:

<img width="373" alt="Screen Shot 2021-08-04 at 1 17 26 PM" src="https://user-images.githubusercontent.com/3644743/128248997-030f6a72-5d41-4b43-8095-9114db160e14.png">

required a refresh.

**Comment by tihuan** [comment] 2021-08-04 22:36
Ahh! The refresh did it 🔥 Previously I was just clicking the developer console and click back in the window to get the new dataset row, and that never triggered the runtime error. Refreshing the page did the trick 👌 

Thanks so much, Brian! Taking a look now

CC: @seve

**Closed** 2021-08-05 16:00 UTC
Labels: bug
